# Generated by Django 4.2.11 on 2024-04-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imgPath', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('genre', models.JSONField()),
                ('language', models.CharField(max_length=100)),
                ('mpaaRating', models.JSONField()),
                ('userRating', models.CharField(max_length=100)),
            ],
        ),
    ]
